### ISSUE TITLE
Gör en klass Currency med attributer och metoder enligt UMLSchemat.

### ISSUE THREAD

**Issue by WazzUppP** [Jakobnr1/MoneyServiceGruppArbete#18]

**Comment by LindbergsKarl** [comment]
Provade att lägga till lite kod för hanteringen av pengar i MoneyBox, Currency. Helt öppet för diskussion om vi kastar upplägget och provar med nytt.

**Comment by PeterAngell** [comment]
ja kollade lite på koden o tycker den ser ok ut har inte haft så mkt tid att koda i helgen kommer sätta mig o göra lite imorgon hoppas jag.

**Comment by LindbergsKarl** [comment]
done

**Comment by LindbergsKarl** [comment]
done
